micronaut:
  application:
    name: ${APPLICATION_NAME:micronaut-app}
  server:
    port: ${MICRONAUT_SERVER_PORT:8071}

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: ${DATASOURCES_DEFAULT_URL:jdbc:postgresql://localhost:5430/demoDB}
    username: ${DATASOURCES_DEFAULT_USERNAME:usr}
    password: ${DATASOURCES_DEFAULT_PASSWORD:pwd}
    driver-class-name: org.postgresql.Driver

# JPA configuration
jpa:
  default:
    entity-scan:
      packages:
        - 'ru.otus.comparison.persistence'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false

# Flyway configuration
flyway:
  datasources:
    default:
      enabled: true


swagger:
  enabled: true
  views:
    enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui
      spec:
        url: /swagger/micronaut-application-1.0.yml

